include(
        ":app",
        ":tools",
        ":requests",
        ":annotations",
        ":storage",
        ":hack",
        ":widget",
        ":kdownloader",
        ":compiler",
        ":hybrid",
        ":design",
        ":jetpack",
        ":image",
        ":anko",
        ":klint",
        ":kanimation",
        ":container",
        ":media",
        ":ndk"
)
rootProject.buildFileName = "build.gradle.kts.kts"